package se.steffy.receptboken;

import android.app.*;
import android.os.Bundle;
import android.graphics.Color;
import android.graphics.Typeface;
import android.content.*;
import android.view.*;
import android.view.inputmethod.InputMethodManager;
import android.widget.*;
import org.json.*;
import java.util.*;

public class MainActivity extends Activity {
    final int BG=Color.rgb(255,248,240), CARD=Color.WHITE, ACCENT=Color.rgb(208,91,52), TEXT=Color.rgb(45,39,35), MUTED=Color.rgb(112,103,96);
    LinearLayout root, list; EditText search; ArrayList<Recipe> recipes=new ArrayList<>(); SharedPreferences prefs; boolean favoritesOnly=false;

    @Override public void onCreate(Bundle b){super.onCreate(b); prefs=getSharedPreferences("recipes",0); load(); showHome();}
    TextView text(String s,int sp,int color){ TextView v=new TextView(this); v.setText(s);v.setTextSize(sp);v.setTextColor(color);v.setPadding(dp(4),dp(5),dp(4),dp(5));return v; }
    Button button(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(15);b.setAllCaps(false);b.setBackgroundColor(ACCENT);return b;}
    int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);} 
    LinearLayout box(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(18),dp(14),dp(18),dp(14));x.setBackgroundColor(CARD);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(12));x.setLayoutParams(p);return x;}

    void base(){ ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(18),dp(18),dp(28));root.setBackgroundColor(BG);scroll.addView(root);setContentView(scroll); }
    void showHome(){base(); LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL); TextView title=text("Min receptbok",30,TEXT);title.setTypeface(null,Typeface.BOLD);head.addView(title,new LinearLayout.LayoutParams(0,-2,1));Button add=button("＋ Nytt recept");head.addView(add);root.addView(head);TextView sub=text("Vad vill du laga idag?",16,MUTED);root.addView(sub);
        search=new EditText(this);search.setHint("Sök maträtt eller ingrediens…");search.setSingleLine();search.setTextSize(16);search.setPadding(dp(16),dp(12),dp(16),dp(12));LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,-2);sp.setMargins(0,dp(14),0,dp(10));root.addView(search,sp);
        CheckBox fav=new CheckBox(this);fav.setText("Visa bara favoriter ★");fav.setChecked(favoritesOnly);root.addView(fav);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);root.addView(list);render("");
        search.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){}public void onTextChanged(CharSequence s,int a,int b,int c){render(s.toString());}public void afterTextChanged(android.text.Editable e){}});fav.setOnCheckedChangeListener((v,c)->{favoritesOnly=c;render(search.getText().toString());});add.setOnClickListener(v->edit(null)); }
    void render(String query){list.removeAllViews();String q=query.toLowerCase(Locale.ROOT);int shown=0;for(Recipe r:recipes){if(favoritesOnly&&!r.fav)continue;if(!q.isEmpty()&&!(r.name+" "+r.category+" "+r.ingredients).toLowerCase(Locale.ROOT).contains(q))continue;shown++;LinearLayout c=box();TextView n=text((r.fav?"★  ":"")+r.name,21,TEXT);n.setTypeface(null,Typeface.BOLD);c.addView(n);c.addView(text(r.category+"  •  "+r.time+" min  •  "+r.portions+" portioner",14,MUTED));c.setOnClickListener(v->detail(r));list.addView(c);}if(shown==0)list.addView(text("Inga recept hittades.",17,MUTED));}
    void detail(Recipe r){base();Button back=button("‹ Tillbaka");back.setOnClickListener(v->showHome());root.addView(back,new LinearLayout.LayoutParams(-2,-2));TextView h=text(r.name,30,TEXT);h.setTypeface(null,Typeface.BOLD);root.addView(h);root.addView(text(r.category+"  •  "+r.time+" min  •  "+r.portions+" portioner",15,MUTED));LinearLayout actions=new LinearLayout(this);Button fav=button(r.fav?"★ Favorit":"☆ Lägg till favorit");Button edit=button("Redigera");actions.addView(fav,new LinearLayout.LayoutParams(0,-2,1));actions.addView(edit,new LinearLayout.LayoutParams(0,-2,1));root.addView(actions);section("Ingredienser",r.ingredients);section("Gör så här",r.steps);fav.setOnClickListener(v->{r.fav=!r.fav;save();detail(r);});edit.setOnClickListener(v->edit(r));}
    void section(String title,String body){TextView h=text(title,22,TEXT);h.setTypeface(null,Typeface.BOLD);h.setPadding(dp(4),dp(22),dp(4),dp(5));root.addView(h);LinearLayout c=box();c.addView(text(body,17,TEXT));root.addView(c);}
    EditText field(String hint,String value,boolean multi){EditText e=new EditText(this);e.setHint(hint);e.setText(value);e.setTextSize(16);e.setPadding(dp(12),dp(10),dp(12),dp(10));if(multi){e.setMinLines(4);e.setGravity(Gravity.TOP);}root.addView(e,new LinearLayout.LayoutParams(-1,-2));return e;}
    void edit(Recipe old){base();Button back=button("‹ Avbryt");back.setOnClickListener(v->{if(old==null)showHome();else detail(old);});root.addView(back,new LinearLayout.LayoutParams(-2,-2));TextView h=text(old==null?"Nytt recept":"Redigera recept",28,TEXT);h.setTypeface(null,Typeface.BOLD);root.addView(h);EditText name=field("Namn på maträtten",old==null?"":old.name,false), cat=field("Kategori, t.ex. Husmanskost",old==null?"":old.category,false), time=field("Tid i minuter",old==null?"":String.valueOf(old.time),false), portions=field("Antal portioner",old==null?"":String.valueOf(old.portions),false), ing=field("Ingredienser – en per rad",old==null?"":old.ingredients,true), steps=field("Gör så här – steg för steg",old==null?"":old.steps,true);Button save=button("Spara recept");LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,-2);bp.setMargins(0,dp(16),0,dp(8));root.addView(save,bp);if(old!=null){Button del=button("Ta bort recept");del.setBackgroundColor(Color.rgb(130,50,45));root.addView(del,bp);del.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Ta bort receptet?").setMessage(old.name).setNegativeButton("Avbryt",null).setPositiveButton("Ta bort",(d,w)->{recipes.remove(old);save();showHome();}).show());}save.setOnClickListener(v->{if(name.getText().toString().trim().isEmpty()){name.setError("Skriv ett namn");return;}Recipe r=old==null?new Recipe():old;r.name=name.getText().toString().trim();r.category=cat.getText().toString().trim();try{r.time=Integer.parseInt(time.getText().toString());}catch(Exception e){r.time=0;}try{r.portions=Integer.parseInt(portions.getText().toString());}catch(Exception e){r.portions=1;}r.ingredients=ing.getText().toString().trim();r.steps=steps.getText().toString().trim();if(old==null)recipes.add(0,r);save();detail(r);});}
    void load(){String data=prefs.getString("data","");if(data.isEmpty()){seed();save();return;}try{JSONArray a=new JSONArray(data);for(int i=0;i<a.length();i++)recipes.add(Recipe.from(a.getJSONObject(i)));}catch(Exception e){seed();}}
    void save(){JSONArray a=new JSONArray();for(Recipe r:recipes)a.put(r.json());prefs.edit().putString("data",a.toString()).apply();}
    void seed(){recipes.clear();recipes.add(new Recipe("Köttfärssås med spaghetti","Pasta",35,4,"500 g köttfärs\n1 gul lök\n2 vitlöksklyftor\n400 g krossade tomater\n2 msk tomatpuré\n1 tsk oregano\nSalt och peppar\n400 g spaghetti","1. Hacka lök och vitlök.\n2. Bryn köttfärsen och tillsätt löken.\n3. Rör ner tomater, tomatpuré och oregano.\n4. Låt sjuda 20 minuter.\n5. Koka spaghettin och servera."));recipes.add(new Recipe("Korvstroganoff","Husmanskost",25,4,"500 g falukorv\n1 gul lök\n2 msk tomatpuré\n3 dl grädde\n1 tsk senap\nSalt och peppar\nRis till servering","1. Koka riset.\n2. Strimla korven och hacka löken.\n3. Stek korv och lök.\n4. Tillsätt tomatpuré, grädde och senap.\n5. Sjud 10 minuter och servera."));recipes.add(new Recipe("Ugnspannkaka","Husmanskost",40,4,"4 ägg\n8 dl mjölk\n4 dl vetemjöl\n1/2 tsk salt\nSmör till formen","1. Sätt ugnen på 225 °C.\n2. Vispa ihop hälften av mjölken med mjölet.\n3. Vispa ner resten av mjölken, ägg och salt.\n4. Häll i smord långpanna.\n5. Grädda 25–30 minuter."));recipes.add(new Recipe("Krämig kycklinggryta","Kyckling",35,4,"600 g kycklingfilé\n1 gul lök\n2 dl crème fraiche\n2 dl grädde\n1 msk kycklingfond\n1 paprika\nSalt och peppar","1. Skär kycklingen i bitar och bryn den.\n2. Hacka lök och paprika och stek med.\n3. Häll i grädde, crème fraiche och fond.\n4. Sjud cirka 15 minuter.\n5. Smaka av och servera med ris."));recipes.add(new Recipe("Kladdkaka","Efterrätt",30,8,"100 g smör\n2 ägg\n3 dl strösocker\n1 1/2 dl vetemjöl\n4 msk kakao\n1 tsk vaniljsocker\n1 krm salt","1. Sätt ugnen på 175 °C.\n2. Smält smöret.\n3. Rör ihop ägg och socker.\n4. Blanda ner övriga ingredienser.\n5. Grädda 15–18 minuter."));}
    static class Recipe{String name="",category="Övrigt",ingredients="",steps="";int time=0,portions=1;boolean fav=false;Recipe(){}Recipe(String n,String c,int t,int p,String i,String s){name=n;category=c;time=t;portions=p;ingredients=i;steps=s;}JSONObject json(){JSONObject o=new JSONObject();try{o.put("name",name);o.put("category",category);o.put("time",time);o.put("portions",portions);o.put("ingredients",ingredients);o.put("steps",steps);o.put("fav",fav);}catch(Exception ignored){}return o;}static Recipe from(JSONObject o)throws Exception{Recipe r=new Recipe();r.name=o.optString("name");r.category=o.optString("category","Övrigt");r.time=o.optInt("time");r.portions=o.optInt("portions",1);r.ingredients=o.optString("ingredients");r.steps=o.optString("steps");r.fav=o.optBoolean("fav");return r;}}
    @Override public void onBackPressed(){showHome();}
}
