package se.steffy.receptboken;

import android.app.*;
import android.os.Bundle;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.content.*;
import android.net.Uri;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.util.*;
import java.util.regex.*;
import java.io.*;

public class MainActivity extends Activity {
 final int BG=Color.rgb(255,248,240),CARD=Color.WHITE,ACCENT=Color.rgb(208,91,52),TEXT=Color.rgb(45,39,35),MUTED=Color.rgb(112,103,96),RED=Color.rgb(130,50,45);
 final int PICK_IMAGE=42,EXPORT_BACKUP=43,IMPORT_BACKUP=44; LinearLayout root,list; EditText search; ArrayList<Recipe> recipes=new ArrayList<>(); ArrayList<String> shopping=new ArrayList<>(); SharedPreferences prefs; boolean favoritesOnly=false; String selectedImage="",categoryFilter="Alla",sortMode="Senast";
 @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("recipes",0);load();loadShopping();home();}
 int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}
 int top(){int id=getResources().getIdentifier("status_bar_height","dimen","android");return(id>0?getResources().getDimensionPixelSize(id):dp(28))+dp(12);}
 GradientDrawable round(int c){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(14));return g;}
 TextView txt(String s,int z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setPadding(dp(4),dp(5),dp(4),dp(5));return v;}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(15);b.setAllCaps(false);b.setPadding(dp(16),dp(10),dp(16),dp(10));b.setBackground(round(ACCENT));return b;}
 LinearLayout card(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(18),dp(14),dp(18),dp(14));x.setBackground(round(CARD));x.setElevation(dp(1));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(12));x.setLayoutParams(p);return x;}
 void base(){getWindow().clearFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);ScrollView s=new ScrollView(this);s.setFillViewport(true);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),top(),dp(18),dp(28));root.setBackgroundColor(BG);s.addView(root);setContentView(s);}
 void full(Button b,int m){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(m),0,dp(5));root.addView(b,p);}
 void title(String s){TextView h=txt(s,30,TEXT);h.setTypeface(null,Typeface.BOLD);root.addView(h);}

 void home(){base();title("Min receptbok");root.addView(txt("Vad vill du laga idag?",16,MUTED));Button add=btn("＋ Nytt recept"),shop=btn("🛒 Lista ("+shopping.size()+")"),backup=btn("💾 Säkerhetskopia");full(add,12);LinearLayout b=new LinearLayout(this);b.addView(shop,half(0,5));b.addView(backup,half(5,0));fullRow(b,6);search=new EditText(this);search.setHint("Sök maträtt eller ingrediens…");search.setSingleLine();search.setTextSize(16);search.setPadding(dp(16),dp(12),dp(16),dp(12));LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,-2);sp.setMargins(0,dp(12),0,dp(6));root.addView(search,sp);categories();Button sort=btn("Sortera: "+sortMode);full(sort,2);CheckBox fav=new CheckBox(this);fav.setText("Visa bara favoriter ★");fav.setChecked(favoritesOnly);root.addView(fav);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);root.addView(list);render("");search.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){}public void onTextChanged(CharSequence s,int a,int b,int c){render(s.toString());}public void afterTextChanged(android.text.Editable e){}});fav.setOnCheckedChangeListener((v,c)->{favoritesOnly=c;render(search.getText().toString());});add.setOnClickListener(v->edit(null));shop.setOnClickListener(v->shopping());backup.setOnClickListener(v->backup());sort.setOnClickListener(v->{sortMode=sortMode.equals("Senast")?"A–Ö":sortMode.equals("A–Ö")?"Kortast tid":"Senast";home();});}
 void categories(){root.addView(txt("Kategorier – svep åt sidan",13,MUTED));HorizontalScrollView scroll=new HorizontalScrollView(this);scroll.setHorizontalScrollBarEnabled(true);LinearLayout row=new LinearLayout(this);LinkedHashSet<String> names=new LinkedHashSet<>();names.add("Alla");for(Recipe r:recipes)if(!r.category.trim().isEmpty())names.add(r.category.trim());for(String name:names){Button b=btn(name);b.setTextSize(13);if(name.equalsIgnoreCase(categoryFilter))b.setBackground(round(TEXT));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,dp(44));p.setMargins(0,0,dp(7),dp(4));row.addView(b,p);b.setOnClickListener(v->{categoryFilter=name;home();});}scroll.addView(row);root.addView(scroll);}
 void render(String query){list.removeAllViews();String q=query.toLowerCase(Locale.ROOT);ArrayList<Recipe> ordered=new ArrayList<>(recipes);if(sortMode.equals("A–Ö"))Collections.sort(ordered,(a,b)->a.name.compareToIgnoreCase(b.name));else if(sortMode.equals("Kortast tid"))Collections.sort(ordered,(a,b)->Integer.compare(a.time,b.time));int shown=0;for(Recipe r:ordered){if(favoritesOnly&&!r.fav)continue;if(!categoryFilter.equals("Alla")&&!r.category.equalsIgnoreCase(categoryFilter))continue;if(!q.isEmpty()&&!(r.name+" "+r.category+" "+r.ingredients).toLowerCase(Locale.ROOT).contains(q))continue;shown++;LinearLayout c=card();if(!r.image.isEmpty())c.addView(photo(r.image),new LinearLayout.LayoutParams(-1,dp(150)));TextView n=txt((r.fav?"★  ":"")+r.name,21,TEXT);n.setTypeface(null,Typeface.BOLD);c.addView(n);c.addView(txt(r.category+"  •  "+r.time+" min  •  "+r.portions+" portioner",14,MUTED));c.setOnClickListener(v->detail(r,r.portions));list.addView(c);}if(shown==0)list.addView(txt("Inga recept hittades.",17,MUTED));}
 ImageView photo(String uri){ImageView im=new ImageView(this);im.setScaleType(ImageView.ScaleType.CENTER_CROP);try{im.setImageURI(Uri.parse(uri));}catch(Exception ignored){}return im;}
 LinearLayout.LayoutParams half(int l,int r){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-2,1);p.setMargins(dp(l),0,dp(r),0);return p;}

 void detail(Recipe r,int portions){base();getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);Button back=btn("‹ Tillbaka");back.setOnClickListener(v->home());root.addView(back,new LinearLayout.LayoutParams(-2,-2));if(!r.image.isEmpty()){LinearLayout.LayoutParams ip=new LinearLayout.LayoutParams(-1,dp(210));ip.setMargins(0,dp(12),0,dp(8));root.addView(photo(r.image),ip);}title(r.name);root.addView(txt(r.category+"  •  "+r.time+" min",15,MUTED));LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);Button minus=btn("−"),plus=btn("＋");TextView count=txt(portions+" portioner",17,TEXT);count.setGravity(Gravity.CENTER);count.setTypeface(null,Typeface.BOLD);row.addView(minus,new LinearLayout.LayoutParams(dp(64),-2));row.addView(count,new LinearLayout.LayoutParams(0,-2,1));row.addView(plus,new LinearLayout.LayoutParams(dp(64),-2));fullRow(row,10);LinearLayout actions=new LinearLayout(this);Button fav=btn(r.fav?"★ Favorit":"☆ Favorit"),edit=btn("Redigera");actions.addView(fav,half(0,5));actions.addView(edit,half(5,0));fullRow(actions,8);Button addShop=btn("🛒 Lägg till i inköpslistan"),cook=btn("👨‍🍳 Starta tillagningsläge"),share=btn("↗ Dela recept");full(addShop,8);full(cook,3);full(share,3);String scaled=scale(r.ingredients,(double)portions/Math.max(1,r.portions));section("Ingredienser",scaled);section("Gör så här",r.steps);minus.setOnClickListener(v->detail(r,Math.max(1,portions-1)));plus.setOnClickListener(v->detail(r,portions+1));fav.setOnClickListener(v->{r.fav=!r.fav;save();detail(r,portions);});edit.setOnClickListener(v->edit(r));cook.setOnClickListener(v->cook(r,portions,0));share.setOnClickListener(v->shareRecipe(r,portions));addShop.setOnClickListener(v->{for(String x:scaled.split("\n"))if(!x.trim().isEmpty())shopping.add(x.trim());saveShopping();Toast.makeText(this,"Tillagt i inköpslistan",Toast.LENGTH_SHORT).show();});}
 void cook(Recipe r,int portions,int step){base();getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);String[] steps=r.steps.split("\n");if(steps.length==0)return;int index=Math.max(0,Math.min(step,steps.length-1));Button close=btn("✕ Avsluta");close.setOnClickListener(v->detail(r,portions));root.addView(close,new LinearLayout.LayoutParams(-2,-2));title(r.name);TextView progress=txt("Steg "+(index+1)+" av "+steps.length,17,MUTED);root.addView(progress);LinearLayout c=card();TextView instruction=txt(steps[index],26,TEXT);instruction.setPadding(dp(12),dp(28),dp(12),dp(28));c.addView(instruction);fullRow(c,20);LinearLayout nav=new LinearLayout(this);Button prev=btn("‹ Föregående"),next=btn(index==steps.length-1?"✓ Klar":"Nästa ›");nav.addView(prev,half(0,5));nav.addView(next,half(5,0));fullRow(nav,12);prev.setEnabled(index>0);prev.setOnClickListener(v->cook(r,portions,index-1));next.setOnClickListener(v->{if(index==steps.length-1)detail(r,portions);else cook(r,portions,index+1);});}
 void shareRecipe(Recipe r,int portions){String body=r.name+"\n"+r.category+" • "+portions+" portioner • "+r.time+" min\n\nINGREDIENSER\n"+scale(r.ingredients,(double)portions/Math.max(1,r.portions))+"\n\nGÖR SÅ HÄR\n"+r.steps+"\n\nDelat från Min receptbok";Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_SUBJECT,r.name);i.putExtra(Intent.EXTRA_TEXT,body);startActivity(Intent.createChooser(i,"Dela recept med"));}
 void fullRow(View v,int m){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(m),0,0);root.addView(v,p);}
 void section(String h,String body){TextView t=txt(h,22,TEXT);t.setTypeface(null,Typeface.BOLD);t.setPadding(dp(4),dp(22),dp(4),dp(5));root.addView(t);LinearLayout c=card();c.addView(txt(body,17,TEXT));root.addView(c);}
 String scale(String src,double f){if(Math.abs(f-1)<.001)return src;Pattern p=Pattern.compile("^(\\d+(?:[.,]\\d+)?)(.*)$");StringBuilder o=new StringBuilder();for(String line:src.split("\n",-1)){Matcher m=p.matcher(line.trim());if(m.matches()){double v=Double.parseDouble(m.group(1).replace(',','.'))*f;String n=Math.abs(v-Math.rint(v))<.01?""+(int)Math.rint(v):String.format(Locale.forLanguageTag("sv-SE"),"%.1f",v);o.append(n).append(m.group(2));}else o.append(line);o.append('\n');}return o.toString().trim();}

 EditText field(String hint,String val,boolean multi){EditText e=new EditText(this);e.setHint(hint);e.setText(val);e.setTextSize(16);e.setPadding(dp(12),dp(10),dp(12),dp(10));if(multi){e.setMinLines(4);e.setGravity(Gravity.TOP);}root.addView(e,new LinearLayout.LayoutParams(-1,-2));return e;}
 void edit(Recipe old){base();selectedImage=old==null?"":old.image;Button back=btn("‹ Avbryt");back.setOnClickListener(v->{if(old==null)home();else detail(old,old.portions);});root.addView(back,new LinearLayout.LayoutParams(-2,-2));title(old==null?"Nytt recept":"Redigera recept");Button image=btn(selectedImage.isEmpty()?"📷 Välj bild":"📷 Byt bild");full(image,8);EditText name=field("Namn på maträtten",old==null?"":old.name,false),cat=field("Kategori",old==null?"":old.category,false),time=field("Tid i minuter",old==null?"":""+old.time,false),portions=field("Antal portioner",old==null?"":""+old.portions,false),ing=field("Ingredienser – en per rad",old==null?"":old.ingredients,true),steps=field("Gör så här – steg för steg",old==null?"":old.steps,true);Button saveBtn=btn("Spara recept");full(saveBtn,16);if(old!=null){Button del=btn("Ta bort recept");del.setBackground(round(RED));full(del,2);del.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Ta bort receptet?").setNegativeButton("Avbryt",null).setPositiveButton("Ta bort",(d,w)->{recipes.remove(old);save();home();}).show());}image.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,PICK_IMAGE);});saveBtn.setOnClickListener(v->{if(name.getText().toString().trim().isEmpty()){name.setError("Skriv ett namn");return;}Recipe r=old==null?new Recipe():old;r.name=name.getText().toString().trim();r.category=cat.getText().toString().trim();r.time=num(time,0);r.portions=Math.max(1,num(portions,1));r.ingredients=ing.getText().toString().trim();r.steps=steps.getText().toString().trim();r.image=selectedImage;if(old==null)recipes.add(0,r);save();detail(r,r.portions);});}
 int num(EditText e,int d){try{return Integer.parseInt(e.getText().toString());}catch(Exception x){return d;}}
 @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(result!=RESULT_OK||data==null||data.getData()==null)return;Uri u=data.getData();if(req==PICK_IMAGE){try{getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}selectedImage=u.toString();Toast.makeText(this,"Bilden är vald",Toast.LENGTH_SHORT).show();}else if(req==EXPORT_BACKUP)writeBackup(u);else if(req==IMPORT_BACKUP)readBackup(u);}

 void backup(){base();Button back=btn("‹ Tillbaka");back.setOnClickListener(v->home());root.addView(back,new LinearLayout.LayoutParams(-2,-2));title("Säkerhetskopia");root.addView(txt("Spara alla recept, favoriter och inköpslistan i en fil. Filen kan återställas på den här eller en annan telefon.",16,MUTED));Button export=btn("Exportera säkerhetskopia"),restore=btn("Återställ från fil");full(export,18);full(restore,5);export.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/json");i.putExtra(Intent.EXTRA_TITLE,"Receptboken-backup.json");startActivityForResult(i,EXPORT_BACKUP);});restore.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("application/json");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,IMPORT_BACKUP);});}
 JSONObject backupJson(){JSONObject o=new JSONObject();JSONArray a=new JSONArray();for(Recipe r:recipes)a.put(r.json());try{o.put("version",1);o.put("recipes",a);o.put("shopping",new JSONArray(shopping));}catch(Exception ignored){}return o;}
 void writeBackup(Uri u){try{OutputStream out=getContentResolver().openOutputStream(u);out.write(backupJson().toString(2).getBytes("UTF-8"));out.close();Toast.makeText(this,"Säkerhetskopian är sparad",Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"Kunde inte spara filen",Toast.LENGTH_LONG).show();}}
 void readBackup(Uri u){try{InputStream in=getContentResolver().openInputStream(u);ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] buf=new byte[4096];int n;while((n=in.read(buf))>0)out.write(buf,0,n);in.close();JSONObject o=new JSONObject(out.toString("UTF-8"));JSONArray a=o.getJSONArray("recipes");ArrayList<Recipe> restored=new ArrayList<>();for(int i=0;i<a.length();i++)restored.add(Recipe.from(a.getJSONObject(i)));recipes.clear();recipes.addAll(restored);shopping.clear();JSONArray s=o.optJSONArray("shopping");if(s!=null)for(int i=0;i<s.length();i++)shopping.add(s.getString(i));save();saveShopping();Toast.makeText(this,"Säkerhetskopian är återställd",Toast.LENGTH_LONG).show();home();}catch(Exception e){Toast.makeText(this,"Filen kunde inte läsas",Toast.LENGTH_LONG).show();}}

 void shopping(){base();Button back=btn("‹ Tillbaka");back.setOnClickListener(v->home());root.addView(back,new LinearLayout.LayoutParams(-2,-2));title("Inköpslista");if(shopping.isEmpty())root.addView(txt("Listan är tom. Lägg till ingredienser från ett recept.",16,MUTED));for(String item:new ArrayList<>(shopping)){CheckBox cb=new CheckBox(this);cb.setText(item);cb.setTextSize(17);cb.setPadding(dp(8),dp(8),dp(8),dp(8));root.addView(cb);cb.setOnCheckedChangeListener((v,c)->{if(c){shopping.remove(item);saveShopping();root.postDelayed(()->shopping(),250);}});}if(!shopping.isEmpty()){Button clear=btn("Töm inköpslistan");clear.setBackground(round(RED));full(clear,16);clear.setOnClickListener(v->{shopping.clear();saveShopping();shopping();});}}
 void loadShopping(){try{JSONArray a=new JSONArray(prefs.getString("shopping","[]"));for(int i=0;i<a.length();i++)shopping.add(a.getString(i));}catch(Exception ignored){}}
 void saveShopping(){prefs.edit().putString("shopping",new JSONArray(shopping).toString()).apply();}
 void load(){String d=prefs.getString("data","");if(d.isEmpty()){seed();save();return;}try{JSONArray a=new JSONArray(d);for(int i=0;i<a.length();i++)recipes.add(Recipe.from(a.getJSONObject(i)));}catch(Exception e){seed();}}
 void save(){JSONArray a=new JSONArray();for(Recipe r:recipes)a.put(r.json());prefs.edit().putString("data",a.toString()).apply();}
 void seed(){recipes.clear();recipes.add(new Recipe("Köttfärssås med spaghetti","Pasta",35,4,"500 g köttfärs\n1 gul lök\n2 vitlöksklyftor\n400 g krossade tomater\n2 msk tomatpuré\n1 tsk oregano\nSalt och peppar\n400 g spaghetti","1. Hacka lök och vitlök.\n2. Bryn köttfärsen och tillsätt löken.\n3. Rör ner tomater, tomatpuré och oregano.\n4. Låt sjuda 20 minuter.\n5. Koka spaghettin och servera."));recipes.add(new Recipe("Korvstroganoff","Husmanskost",25,4,"500 g falukorv\n1 gul lök\n2 msk tomatpuré\n3 dl grädde\n1 tsk senap\nSalt och peppar","1. Stek korv och lök.\n2. Tillsätt övriga ingredienser.\n3. Sjud 10 minuter."));recipes.add(new Recipe("Ugnspannkaka","Husmanskost",40,4,"4 ägg\n8 dl mjölk\n4 dl vetemjöl\n0,5 tsk salt","1. Sätt ugnen på 225 °C.\n2. Vispa ihop allt.\n3. Grädda 25–30 minuter."));recipes.add(new Recipe("Krämig kycklinggryta","Kyckling",35,4,"600 g kycklingfilé\n1 gul lök\n2 dl crème fraiche\n2 dl grädde\n1 paprika","1. Bryn kycklingen.\n2. Tillsätt resten.\n3. Sjud 15 minuter."));recipes.add(new Recipe("Kladdkaka","Efterrätt",30,8,"100 g smör\n2 ägg\n3 dl strösocker\n1,5 dl vetemjöl\n4 msk kakao","1. Sätt ugnen på 175 °C.\n2. Blanda allt.\n3. Grädda 15–18 minuter."));}
 static class Recipe{String name="",category="Övrigt",ingredients="",steps="",image="";int time=0,portions=1;boolean fav=false;Recipe(){}Recipe(String n,String c,int t,int p,String i,String s){name=n;category=c;time=t;portions=p;ingredients=i;steps=s;}JSONObject json(){JSONObject o=new JSONObject();try{o.put("name",name);o.put("category",category);o.put("time",time);o.put("portions",portions);o.put("ingredients",ingredients);o.put("steps",steps);o.put("fav",fav);o.put("image",image);}catch(Exception ignored){}return o;}static Recipe from(JSONObject o){Recipe r=new Recipe();r.name=o.optString("name");r.category=o.optString("category","Övrigt");r.time=o.optInt("time");r.portions=o.optInt("portions",1);r.ingredients=o.optString("ingredients");r.steps=o.optString("steps");r.fav=o.optBoolean("fav");r.image=o.optString("image");return r;}}
 @Override public void onBackPressed(){home();}
}
