plugins { id 'com.android.application' }

android {
    namespace 'se.steffy.receptboken'
    compileSdk 35
    defaultConfig {
        applicationId 'se.steffy.receptboken'
        minSdk 26
        targetSdk 35
        versionCode 28
        versionName '3.0'
    }
}

dependencies {
    implementation 'com.google.mlkit:text-recognition:16.0.1'
}
